baseurl = "https://www.synax.io"
DefaultContentLanguage = "en"
#DefaultContentLanguage = "ja"
title = "synax.io"
theme = "beautifulhugo"
metaDataFormat = "yaml"
pygmentsStyle = "trac"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
#pygmentsUseClassic = true
#pygmentOptions = "linenos=inline"
disqusShortname = "synax-blog"
googleAnalytics = "UA-118377378-1"

[Params]
  homeTitle = "synax.io" # Set a different text for the header on the home page
  subtitle = "This is the official blog of stefan henseler"
  logo = "img/avatar-icon.png"
  favicon = "img/favicon.ico"
  dateFormat = "January 2, 2006"
  commit = false
  rss = true
  comments = true
  readingTime = true
  useHLJS = true
  socialShare = true
  gcse = "005966820730073608111:mse7i1v6bx0" # Get your code from google.com/cse. Make sure to go to "Look and Feel" and change Layout to "Full Width" and Theme to "Classic"

#[[Params.bigimg]]
#  src = "img/triangle.jpg"
#  desc = "Triangle"
#[[Params.bigimg]]
#  src = "img/sphere.jpg"
#  desc = "Sphere"
#  # position: see values of CSS background-position.
#  position = "center top"
#[[Params.bigimg]]
#  src = "img/hexagon.jpg"
#  desc = "Hexagon"

[Author]
  name = "Stefan Henseler"
  website = "synax.io"
  email = "stefan.henseler@synax.ch"
  #facebook = ""
  #googleplus = "+username" # or xxxxxxxxxxxxxxxxxxxxx
  github = "synax"
  #gitlab = "username"
  #bitbucket = "username"
  twitter = "stefanhenseler"
  #reddit = "username"
  linkedin = "synax"
  xing = "Stefan_Henseler3"
  #stackoverflow = "users/XXXXXXX/username"
  #snapchat = "username"
  #instagram = "username"
  #youtube = "user/username" # or channel/channelname
  #soundcloud = "username"
  #spotify = "username"
  #bandcamp = "username"
  #itchio = "username"
  #vk = "username"
  #paypal = "username"
  #telegram = "username"

[[menu.main]]
    name = "Blog"
    url = ""
    weight = 1

[[menu.main]]
    name = "About"
    url = "page/about/"
    weight = 3

[[menu.main]]
    name = "Tags"
    url = "tags"
    weight = 3
